version: '3.2'

services:
  zksync:
    build:
      dockerfile_inline: |
        FROM rust:1.71
        WORKDIR /app
        COPY . .
        RUN apt-get update && apt-get install -y cmake pkg-config libssl-dev clang && rm -rf /var/lib/apt/lists/*
        RUN cargo install --path . --locked
        EXPOSE 8011
        CMD ["era_test_node", "run"]
    ports:
      - "8011:8011"
