version: '3.2'

services:
  zksync:
    platform: linux/amd64
    build:
      dockerfile_inline: |
        FROM ubuntu:latest
        WORKDIR /app
        RUN apt-get update \
          && apt-get install -y curl \
          && apt-get clean \
          && rm -rf /var/lib/apt/lists/*
        RUN curl -o era_test_node.tar.gz -L https://github.com/matter-labs/era-test-node/releases/download/v0.1.0-alpha.3/era_test_node-v0.1.0-alpha.3-x86_64-unknown-linux-gnu.tar.gz
        RUN tar xz -f era_test_node.tar.gz -C /usr/local/bin/
        RUN chmod +x /usr/local/bin/era_test_node
        EXPOSE 8011
        CMD ["era_test_node", "run"]
    ports:
      - "8011:8011"
