version: '3.2'

services:
  portal-dockerized-node:
    environment:
      - NODE_TYPE=dockerized
    build:
      dockerfile_inline: |
        FROM node:18
        WORKDIR /app
        COPY . .
        RUN npm ci --quiet --no-audit
        RUN npm run generate:node:docker
        EXPOSE 3000
        CMD ["npm", "run", "preview"]
    ports:
      - "3000:3000"
